<div class="row-fluid sortable">		
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon user"></i><span class="break"></span>Members</h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                <thead>
                    <tr>
                        <th>序号</th>
                        <th>分类名称</th>
                        <th>分类描述</th>
                        <th>分类状态</th>
                        <th>路径</th>
                        <th>创建时间</th>
                        <th>操作</th>
                    </tr>
                </thead>   
                <tbody>
                    <?php
                    $cates_arr = $this->objToArray->ohYeah($pages->items);
                    $items = $this->tree->_tree($cates_arr, $parent_id = 0, $level = 0);
                    $items = $this->arrayToObj->tran($items);
                    foreach ($items as $vs) {
                        ?>
                        <tr>
                            <td><?php echo $vs->id; ?></td>

                            <td>
                                <?php echo str_repeat("&nbsp;&nbsp;&nbsp;&nbsp;", $vs->level); ?>
    <?php echo $vs->name; ?>
                            </td>
                            <td><?php echo $vs->description; ?></td>
                            <td><?php echo $vs->status; ?></td>
                            <td><?php echo $vs->path; ?></td>
                            <td><?php echo $vs->ctime; ?></td>
                            <td class="center">
                                <a class="btn btn-success" href="#">
                                    <i class="halflings-icon white zoom-in"></i>  
                                </a>
                                <a class="btn btn-info" href="#">
                                    <i class="halflings-icon white edit"></i>  
                                </a>
                                <a class="btn btn-danger" href="#">
                                    <i class="halflings-icon white trash"></i> 
                                </a>
                            </td>
                        </tr>
<?php } ?>

                </tbody>
            </table>   
            <a href="/category/index">First</a>
            <a href="/category/index?page=<?= $pages->before; ?>">Previous</a>
            <a href="/category/index?page=<?= $pages->next; ?>">Next</a>
            <a href="/category/index?page=<?= $pages->last; ?>">Last</a>

<?php echo "You are in page ", $pages->current, " of ", $pages->total_pages; ?>
        </div>
    </div><!--/span-->

</div><!--/row-->





