<div class="row-fluid sortable">		
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon user"></i><span class="break"></span><?php ?></h2>
            <div class="box-icon">
                <a href="/category/addCategory">添加分类</a>
                <a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                <thead>
                    <tr>
                        <!--<th>序号</th>-->
                        <th>分类名称</th>
                        <th>分类描述</th>
                        <!--<th>分类状态</th>-->
                        <th>可见性</th>
                        <th>创建时间</th>
                        <th>修改时间</th>
                        <th>操作</th>
                    </tr>
                </thead>   
                <tbody>
                    <?php
                    $cates_arr = $this->objToArray->ohYeah($pages);
                    $items = $this->tree->_tree($cates_arr, $parent_id = 0, $level = 0);
                    foreach ($items as $vs) {
                        ?>
                        <tr>

                            <td>
                                <?php echo str_repeat("&nbsp;&nbsp;&nbsp;&nbsp;", $vs['level']); ?>
    <?php echo $vs['name']; ?>
                            </td>
                            <td><?php echo $vs['description']; ?></td>
                            <td><?php echo $vs['visibility']; ?></td>
                            <td><?php echo $vs['ctime']; ?></td>
                            <td><?php echo $vs['mtime']; ?></td>
                            <td class="center">
                                <a class="btn btn-success" href="/category/showCategory/<?php echo $vs['id'];?>">
                                    <i class="halflings-icon white zoom-in"></i>  
                                </a>
                                <a class="btn btn-info" href="/category/editCategory/<?php echo $vs['id'];?>">
                                    <i class="halflings-icon white edit"></i>  
                                </a>
                               
                            </td>
                        </tr>
<?php } ?>

                </tbody>
            </table>   
            
        </div>
    </div><!--/span-->

</div><!--/row-->





