<ul class="breadcrumb">
				<li>
					<i class="icon-home"></i>
					<a href="index.html">Home</a>
					<i class="icon-angle-right"></i> 
				</li>
				<li>
					<i class="icon-edit"></i>
					<a href="#">编辑模板</a>
				</li>
			</ul>
			
			<div class="row-fluid sortable">
				<div class="box span12">
					<div class="box-header" data-original-title>
						<h2><i class="halflings-icon edit"></i><span class="break"></span>编辑模板</h2>
						<div class="box-icon">
							<a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
							<a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
							<a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
						</div>
					</div>
					<div class="box-content">
						<?php echo \Phalcon\Tag::form(array("", "method" => "post",'class'=>'form-horizontal')); ?>
						  <?php echo \Phalcon\Tag::hiddenField(array("id","value"=>$info->id)) ?>
						  <fieldset>
							
							<div class="control-group">
							  <label class="control-label" for="typeahead">模板名字</label>
							  <div class="controls">
								<?php echo \Phalcon\Tag::textField(array("name", "class" => "span6 typeahead" , "value"=>$info->name)) ?>
							  </div>
							</div>
							
							<div class="control-group">
							  <label class="control-label" for="typeahead">所属分类</label>
							  <div class="controls">
								<?php 
								  echo \Phalcon\Tag::selectStatic(array(
								  				"category_id",
								  				Category::find(),
								  				"using" => array("id", "name"),
												"value"=>$info->category_id
								  		 	));  ?>
							  </div>
							</div>
							
							<div class="control-group">
							  <label class="control-label" for="typeahead">模板描述</label>
							  <div class="controls">
								<?php echo \Phalcon\Tag::textArea(array("decription", "class" => "span6 typeahead",'rows'=>5,"value"=>$info->decription)) ?>
							  </div>
							</div>
							
							<div class="control-group">
							  <label class="control-label" for="typeahead">模板内容</label>
							  <div class="controls">
								<?php echo \Phalcon\Tag::textArea(array("content", "class" => "span6 typeahead",'rows'=>15 ,'id'=>'content_source', "value"=>$info->content)) ?>
							  </div>
							</div>
							
							<div class="control-group">
							  <label class="control-label" for="typeahead">模板引擎</label>
							  <div class="controls">
								  <?php 
								  echo \Phalcon\Tag::selectStatic("engine", array('PHP' => 'PHP', 'Smarty' => 'Smarty','Volt'=>'Volt',"value"=>$info->engine));
								  ?>
								  
							  </div>
							</div>
							
							
							
							<div class="control-group">
							  <label class="control-label" for="typeahead">模板状态</label>
							  <div class="controls">
								  <?php 
								  echo \Phalcon\Tag::selectStatic("status", array('Y' => '启用', 'N' => '关闭',"value"=>$info->status));
								  ?>
								</div>
							</div>
							
							<div class="form-actions">
							  <?php echo \Phalcon\Tag::submitButton(array("保存",'class'=>'btn btn-primary')) ?>
						
							  <button type="reset" class="btn">取消</button>
							</div>
						  </fieldset> 
						<?php echo \Phalcon\Tag::endForm(); ?>
					</div>
				</div><!--/span-->

			</div><!--/row-->


	</div><!--/.fluid-container-->
	
