			<ul class="breadcrumb">
				<li>
					<i class="icon-home"></i>
					<a href="/">Home</a> 
					<i class="icon-angle-right"></i>
				</li>
				<li><a href="#">模板列表</a></li>
				<li>
			</ul>

			<div class="row-fluid sortable">		
				<div class="box span12">
					<div class="box-header" data-original-title>
						<h2><i class="halflings-icon align-justify"></i><span class="break"></span>模板列表</h2>
						<div class="box-icon">
							<a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
							<a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
							<a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
						</div>
					</div>
					<div class="box-content">
						<div class="row-fluid">
							 
							<div class="span11">
							<?php echo \Phalcon\Tag::form(array("", "method" => "post",'class'=>'form-horizontal')); ?>
								<div class="dataTables_filter">
								分类：<select name="category_id">
								<option value="">--</option>
							  <?php 
                                   $cates_arr = $this->objToArray->ohYeah(Category::find());
                                   $items = $this->tree->_tree($cates_arr, $parent_id = 0, $level = 0);
                                   foreach ($items as $vs) :?>
                                        <option value="<?php echo $vs['id'];?>" 
                                        <?php echo (isset($where['category_id']) && $where['category_id']==$vs['id']) ? 'selected' : '' ?>>
                                             <?php echo str_repeat("&nbsp;&nbsp;&nbsp;&nbsp;",$vs['level']);?>
                                                 <?php echo $vs['name'];?>
                                              </option>
                                            <?php endforeach;?>
                                </select>
                                	名字：<?php echo \Phalcon\Tag::textField(array("name", "class" => "span2 typeahead" , "value"=>isset($where['name']) ? $where['name'] : '')) ?>
                                	状态：<?php echo \Phalcon\Tag::selectStatic(array("status", array(''=>'--','Enabled' => '启用', 'Disabled' => '关闭'),'class'=>'span2',"value"=>isset($where['status']) ? $where['status'] : ''));?>
                                	类型：<?php echo \Phalcon\Tag::selectStatic(array("type", array(''=>'--','Category' => '分类', 'List' => '列表','Detail'=>'内容页'),'class'=>'span2',"value"=>isset($where['type']) ? $where['type'] : ''));?>
                                <?php echo \Phalcon\Tag::submitButton(array("查询",'class'=>'btn btn-small btn-primary')) ?>
								</div>
							</div>
							<?php echo \Phalcon\Tag::endForm()?>
							
							
						</div>
						<table class="table table-striped table-bordered bootstrap-datatable datatable">
						  <thead>
							  <tr>
								  <th width="1%">ID</th>
								  <th width="3%">所属分类</th>
								  <th width="4%">模板名字</th>
								  <th width="7%">模板描述</th>
								  <th width="2%">模板状态</th>
								  <th width="2%">模板类型</th><!--  <th width="2%">模板引擎</th>-->
								  <th width="4%">创建时间</th>
								  <th width="4%">修改时间</th>
								  <th width="6%">操作</th>
							  </tr>
						  </thead>   
						  <tbody>
						  <?php foreach ($page->items as $item):?>
							<tr>
								<td><?php echo $item->template->id;?></td>
								<td><?php echo $item->cname;?></td>
								<td><?php echo $item->template->name;?></td>
								<td><?php echo $item->template->decription;?></td>
								<td><?php echo $item->template->status;?></td>
								<td><?php echo $item->template->type;?></td><!--  <td><?php echo $item->template->engine;?></td>-->
								<td><?php echo $item->template->ctime;?></td>
								<td><?php echo $item->template->mtime;?></td>
								<td class="center">
									<a class="btn btn-success" href="/template/preview/<?php echo $item->template->id ?>">
										<i class="halflings-icon white zoom-in"></i>  
									</a>
									<a class="btn btn-info" href="/template/edit/<?php echo $item->template->id ?>">
										<i class="halflings-icon white edit"></i>  
									</a>
									<a class="btn btn-danger" href="/template/delete/<?php echo $item->template->id ?>">
										<i class="halflings-icon white trash"></i> 
									</a>
								</td>
							</tr>
							<?php endforeach;?>
						</tbody>
					  </table> 
					  <div class="row-fluid">
						  <div class="span12 center">
							  <div class="dataTables_paginate paging_bootstrap pagination">
						  	  	  <span class="page_text">共有 <?php echo $page->total_items;?> 条记录, 每页显示 <?php echo $page->pageSize;?> 条, 当前<?php echo $page->current;?>/<?php echo $page->total_pages;?> 页:</span>
								  <ul>
								  	  <li class="prev"><a href="/template">First</a></li>
									  <li class="prev"><a href="/template/list/<?php echo $page->before;?>/<?php echo $page->pageSize;?>">← Previous</a></li>
									  <li class="next"><a href="/template/list/<?php echo $page->next;?>/<?php echo $page->pageSize;?>">Next → </a></li>
									  <li class=""><a href="/template/list/<?php echo $page->last;?>/<?php echo $page->pageSize;?>">Last</a></li>
								  </ul>
								  <select name="pagesize" size="1" class="pagesize" onchange="location.href='/template/list/1/'+this.value;">
									<option value="10"<?php if($page->pageSize==10):?> selected="selected"<?php endif;?>>10</option>
									<option value="25"<?php if($page->pageSize==25):?> selected="selected"<?php endif;?>>25</option>
									<option value="50"<?php if($page->pageSize==50):?> selected="selected"<?php endif;?>>50</option>
									<option value="100"<?php if($page->pageSize==100):?> selected="selected"<?php endif;?>>100</option>
								</select> 
							  </div>
						  </div>
					  </div>           
					</div>
				</div><!--/span-->
			
			</div><!--/row-->
