			<ul class="breadcrumb">
				<li>
					<i class="icon-home"></i>
					<a href="/">Home</a> 
					<i class="icon-angle-right"></i>
				</li>
				<li><a href="#">模板列表</a></li>
			</ul>

			<div class="row-fluid sortable">		
				<div class="box span12">
					<div class="box-header" data-original-title>
						<h2><i class="halflings-icon align-justify"></i><span class="break"></span>模板列表</h2>
						<div class="box-icon">
							<a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
							<a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
							<a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
						</div>
					</div>
					<div class="box-content">
						<div class="row-fluid">
							
							<div class="span6">
								<div class="dataTables_filter" id="DataTables_Table_0_filter">
									<label>Search: <input type="text" aria-controls="DataTables_Table_0"></label>
								</div>
							</div>
						</div>
						<table class="table table-striped table-bordered bootstrap-datatable datatable">
						  <thead>
							  <tr>
								  <th>ID</th>
								  <th>所属分类</th>
								  <th>模板名字</th>
								  <th>模板描述</th>
								  <th>模板状态</th>
								  <th>模板引擎</th>
								  <th>创建时间</th>
								  <th>修改时间</th>
								  <th>操作</th>
							  </tr>
						  </thead>   
						  <tbody>
						  <?php foreach ($page->items as $item):?>
							<tr>
								<td><?php echo $item->id;?></td>
								<td class="center"><?php echo $item->category_id;?></td>
								<td class="center"><?php echo $item->name;?></td>
								<td><?php echo $item->decription;?></td>
								<td><?php echo $item->status;?></td>
								<td><?php echo $item->engine;?></td>
								<td><?php echo $item->ctime;?></td>
								<td><?php echo $item->mtime;?></td>
								<td class="center">
									<a class="btn btn-success" href="/template/view/<?php echo $item->id ?>">
										<i class="halflings-icon white zoom-in"></i>  
									</a>
									<a class="btn btn-info" href="/template/edit/<?php echo $item->id ?>">
										<i class="halflings-icon white edit"></i>  
									</a>
									<a class="btn btn-danger" href="/template/delete/<?php echo $item->id ?>">
										<i class="halflings-icon white trash"></i> 
									</a>
								</td>
							</tr>
							<?php endforeach;?>
						</tbody>
					  </table> 
					  <div class="row-fluid">
						  <div class="span12 center">
							  <div class="dataTables_paginate paging_bootstrap pagination">
						  	  	  <span class="page_text">共有 <?php echo $page->total_items;?> 条记录, 每页显示 <?php echo $page->pageSize;?> 条, 当前<?php echo $page->current;?>/<?php echo $page->total_pages;?> 页:</span>
								  <ul>
								  	  <li class="prev"><a href="/article">First</a></li>
									  <li class="prev"><a href="/article/list/<?php echo $page->before;?>/<?php echo $page->pageSize;?>">← Previous</a></li>
									  <li class="next"><a href="/article/list/<?php echo $page->next;?>/<?php echo $page->pageSize;?>">Next → </a></li>
									  <li class=""><a href="/article/list/<?php echo $page->last;?>/<?php echo $page->pageSize;?>">Last</a></li>
								  </ul>
								  <select name="pagesize" size="1" class="pagesize" onchange="location.href='/article/1/'+this.value;">
									<option value="10"<?php if($page->pageSize==10):?> selected="selected"<?php endif;?>>10</option>
									<option value="25"<?php if($page->pageSize==25):?> selected="selected"<?php endif;?>>25</option>
									<option value="50"<?php if($page->pageSize==50):?> selected="selected"<?php endif;?>>50</option>
									<option value="100"<?php if($page->pageSize==100):?> selected="selected"<?php endif;?>>100</option>
								</select> 
							  </div>
						  </div>
					  </div>           
					</div>
				</div><!--/span-->
			
			</div><!--/row-->
