			<ul class="breadcrumb">
				<li>
					<i class="icon-home"></i>
					<a href="/">Home</a> 
					<i class="icon-angle-right"></i>
				</li>
				<li><a href="#">模板预览</a></li>
				<li>
			</ul>

			<div class="row-fluid sortable">		
				<div class="box span12">
					<div class="box-header" data-original-title>
						<h2><i class="halflings-icon align-justify"></i><span class="break"></span>分页页预览</h2>
						<div class="box-icon">
							<a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
							<a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
							<a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
						</div>
					</div>
					<div class="box-content">
						<div class="row-fluid">
							 
							<div class="span11">
							<?php echo \Phalcon\Tag::form(array("", "method" => "post",'class'=>'form-horizontal')); ?>
								<div class="dataTables_filter">
								分类：<select name="category_id" id="category_id">
								<option value="">--</option>
							  <?php 
                                   $cates_arr = $this->objToArray->ohYeah(Category::find());
                                   $items = $this->tree->_tree($cates_arr, $parent_id = 0, $level = 0);
                                   foreach ($items as $vs) :?>
                                        <option value="<?php echo $vs['id'];?>" 
                                        <?php echo (isset($where['category_id']) && $where['category_id']==$vs['id']) ? 'selected' : '' ?>>
                                             <?php echo str_repeat("&nbsp;&nbsp;&nbsp;&nbsp;",$vs['level']);?>
                                                 <?php echo $vs['name'];?>
                                              </option>
                                            <?php endforeach;?>
                                </select>
                                	
                                	模板：<?php 
                                	
                                	echo \Phalcon\Tag::selectStatic(array(
                                			"template_id",
                                			Template::find('status= \'Enabled\' AND type= \''.$type.'\''),
                                			"using" => array("id", "name"),
                                			"value"=>''
                                	));
                                	
                                	?>
                                <?php echo \Phalcon\Tag::submitButton(array("查询",'class'=>'btn btn-small btn-primary')) ?>
								</div>
							</div>
							<?php echo \Phalcon\Tag::endForm()?>
							
							
						</div>
						<div id="loading" class="loading">
						
						
						</div>
						
					  </table> 
					            
					</div>
				</div><!--/span-->
			
			</div><!--/row-->
			
			<script>
			$(document).ready(function(){
				$('.btn-primary').click(function(){
					var template_id = $('#template_id').val();
					var category_id = $('#category_id').val();
					if(!template_id){
						$('#myModal>.modal-body>p').html('请选择模板');
						$('#myModal').modal('show');
						return false;
					}
					if(!category_id){
						$('#myModal>.modal-body>p').html('请选择分类');
						$('#myModal').modal('show');
						return false;
					}
					var url = "<?php echo $url ?>";
					url = url.replace(':template_id',template_id)
								.replace(':category_id',category_id);
					/**
					$.ajax({
				        type: "POST",
				        url: url,
				        data: {},
				        async:false,
				        success: function(data){
				        	$('#loading').html(data);
				    	}
				    });
					**/
					$('#loading').html('<iframe border="0" vspace="0" hspace="0" marginWidth="0" marginHeight="0" frameSpacing="0" frameBorder="0" scrolling="no" width="100%" height="500px" class="form-horizontal" src="'+url+'">');
					return false;
				})
				$('#template_id').change(function(){
					$(".btn-primary").trigger("click");
				});
			});
			
			</script>
