<script type="text/javascript">


</script>
<div class="row-fluid sortable">		
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon user"></i><span class="break"></span><?php ?></h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
            </div>
        </div>
        
        <div class="box-content">
            <div class="row-fluid">
							<div class="">
								
                                                            <div style="float:left"><a href="/contact/upload"><input  type="button" value="导入联系人" class="btn btn-primary btn-search" /></a></div>
							</div>
						</div>
            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                <thead>
                    <tr>
                        
                        <th>联系人姓名</th>
                        <th>联系人手机号码</th>
                        <th>联系人邮箱</th>
                        <th>备注描述</th>
                        <th>订阅状态</th>
                        <th>创建时间</th>
                        <th>修改时间</th>
                    </tr>
                </thead>   
                <tbody>
                    <?php
                    $contact_arr = $this->objToArray->ohYeah($contact);
                    foreach ($contact_arr as $vs) {
                        ?>
                        <tr>
                            <td ><?php echo $vs['name']?></td>
                            <td ><?php echo $vs['mobile_digest']?></td>
                            <td ><?php echo $vs['email_digest']?></td>
                            <td><?php echo $vs['description']; ?></td>
                            <td ><?php echo $vs['status']?></td>
                            <td><?php echo $vs['ctime']; ?></td>
                            <td ><?php echo $vs['mtime']?></td>
                            <td class="center">
                                <a title="编辑联系人" class="btn btn-info" href="/contact/edit/<?php echo $vs['id']; ?>">
                                    <i class="halflings-icon white edit"></i>  
                                </a>
                            </td>
                        </tr>
<?php } ?>

                </tbody>
            </table>   
            
        </div>
    </div><!--/span-->

</div><!--/row-->
<script language="javascript" type="text/javascript">
    $(function(){
        $("#language").change(function(){
            var language = $(this).children('option:selected').val();
            $('.datatable tbody tr').hide();
            $('.datatable tbody tr[language="'+language+'"]').show();
//            $.post('index',{language:language},function(data){
//                if(!data.status){
//            },'json');
        });

      });
</script>





