			<ul class="breadcrumb">
				<li>
					<i class="icon-home"></i>
					<a href="/">Home</a>
					<i class="icon-angle-right"></i> 
				</li>
				<li>
					<i class="icon-edit"></i>
					<a href="#">编辑文章</a>
				</li>
			</ul>
			
			<div class="row-fluid sortable">
				<div class="box span12">
					<div class="box-header" data-original-title>
						<h2><i class="halflings-icon edit"></i><span class="break"></span>文章</h2>
						<div class="box-icon">
							<a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
							<a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
							<a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
						</div>
					</div>
					<div class="box-content">
						<form class="form-horizontal" method="post" action="" name="createForm" id="createForm" enctype="multipart/form-data">
						  <fieldset>
							<div class="control-group">
							  <label class="control-label" for="typeahead">文章标题 </label>
							  <div class="controls">
								<input type="text" class="span6 typeahead" id="title" name="title" value="" />
								<p class="help-block"></p>
							  </div>
							</div>
							<div class="control-group">
							  <label class="control-label" for="language">语言 </label>
							  <div class="controls">
								<select name="language" id="language">
									<option value="">请选择</option>
									<option value="cn">CN</option>
									<option value="tw">TW</option>
									<option value="en">EN</option>
								</select>
							  </div>
							</div>
							<div class="control-group">
							  <label class="control-label" for="category_id">事业部分类 </label>
							  <div class="controls">
								<select name="division_category_id" id="division_category_id">
									<option value="">请选择</option>
									<?php
				                    $cates_arr = $this->objToArray->ohYeah($divisionCategory);
				                    $items = $this->tree->_tree($cates_arr, $parent_id = 0, $level = 0);
				                    foreach ($items as $vs) :
				                        ?>
									<option value="<?php echo $vs['id'];?>">
									<?php echo str_repeat("&nbsp;&nbsp;&nbsp;&nbsp;", $vs['level']); ?>
    								<?php echo $vs['name']; ?>
    								</option>
									<?php endforeach;?>
								</select>
							  </div>
							</div>
							<!--div class="control-group">
							  <label class="control-label" for="division_category_id">事业部分类 </label>
							  <div class="controls">
								<select name="division_category_id" id="division_category_id">
									<option value="">请选择</option>
									<option value="cn">CN</option>
									<option value="tw">TW</option>
									<option value="en">EN</option>
								</select>
							  </div>
							</div-->

							<div class="control-group">
							  <label class="control-label" for="image">图片</label>
							  <div class="controls">
								<input class="input-file uniform_on" id="image" name="image" type="file" />
								<input type="hidden" name="hdimage" value="" />
							  </div>
							</div>  
							<div class="control-group">
								<label class="control-label">可见性</label>
								<div class="controls">
								  <label class="radio">
									<input name="visibility" type="radio" value="Visible" /> 可见
								  </label>
								  <div style="clear:both"></div>
								  <label class="radio">
									<input name="visibility" type="radio" value="Hidden" /> 不可见
								  </label>
								</div>
							</div>
							<div class="control-group">
								<label class="control-label">分享</label>
								<div class="controls">
								  <label class="radio">
									<input name="share" type="radio" value="Y" /> 是
								  </label>
								  <div style="clear:both"></div>
								  <label class="radio">
									<input name="share" type="radio" value="N" /> 否
								  </label>
								</div>
							</div>
							<!--div class="control-group">
								<label class="control-label">状态</label>
								<div class="controls">
								  <label class="radio">
									<input name="status" type="radio" value="Hidden" /> 隐藏
								  </label>
								  <div style="clear:both"></div>
								  <label class="radio">
									<input name="status" type="radio" value="Disabled" /> 无效
								  </label>
								  <div style="clear:both"></div>
								  <label class="radio">
									<input name="status" type="radio" value="Enabled" /> 有效
								  </label>
								</div>
							</div-->  
							
							<div class="control-group hidden-phone">
							  <label class="control-label" for="content">文章内容</label>
							  <div class="controls">
								<textarea class="cleditor" id="content" name="content" rows="8" style="width:700px;height:300px;"></textarea>
							  </div>
							</div>         
							<div class="control-group hidden-phone">
							  <label class="control-label" for="keyword">关键字SEO</label>
							  <div class="controls">
								<input type="text" class="span6" id="keyword" name="keyword" value="" />
							  </div>
							</div>        
							<div class="control-group hidden-phone">
							  <label class="control-label" for="description">描述SEO</label>
							  <div class="controls">
								<input type="text" class="span6" id="description" name="description" value="" />
							  </div>
							</div>    
							<div class="control-group hidden-phone">
							  <label class="control-label" for="author">作者</label>
							  <div class="controls">
								<input type="text" class="input-xlarge" id="author" name="author" value="" />
							  </div>
							</div>
							<div class="form-actions">
							  <button type="submit" class="btn btn-primary">保存</button>
							  <button type="reset" class="btn">取消</button>
							</div>
						  </fieldset>
						</form>   

					</div>
				</div><!--/span-->

			</div><!--/row-->
			<script type="text/javascript">
				var editor;
				KindEditor.ready(function(K) {
					editor = K.create('textarea[name="content"]', {
						cssPath : '/css/editor/code/prettify.css',
						uploadJson : '../php/upload_json.php',
						fileManagerJson : '../php/file_manager_json.php',
						allowFileManager : true,
						afterCreate : function() {
							var self = this;
							K.ctrl(document, 13, function() {
								self.sync();
								K('form[name=createForm]')[0].submit();
							});
							K.ctrl(self.edit.doc, 13, function() {
								self.sync();
								K('form[name=createForm]')[0].submit();
							});
						}
					});
					/*K('input[name=getHtml]').click(function(e) {
						alert(editor.html());
					});
					K('input[name=isEmpty]').click(function(e) {
						alert(editor.isEmpty());
					});
					K('input[name=getText]').click(function(e) {
						alert(editor.text());
					});
					K('input[name=selectedHtml]').click(function(e) {
						alert(editor.selectedHtml());
					});
					K('input[name=setHtml]').click(function(e) {
						editor.html('<h3>Hello KindEditor</h3>');
					});
					K('input[name=setText]').click(function(e) {
						editor.text('<h3>Hello KindEditor</h3>');
					});
					K('input[name=insertHtml]').click(function(e) {
						editor.insertHtml('<strong>插入HTML</strong>');
					});
					K('input[name=appendHtml]').click(function(e) {
						editor.appendHtml('<strong>添加HTML</strong>');
					});
					K('input[name=clear]').click(function(e) {
						editor.html('');
					});*/
				});
			</script>