			<ul class="breadcrumb">
				<li>
					<i class="icon-home"></i>
					<a href="/">Home</a> 
					<i class="icon-angle-right"></i>
				</li>
				<li><a href="#">文章列表</a></li>
			</ul>

			<div class="row-fluid sortable">		
				<div class="box span12">
					<div class="box-header" data-original-title>
						<h2><i class="halflings-icon align-justify"></i><span class="break"></span>文章列表</h2>
						<div class="box-icon">
							<a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
							<a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
							<a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
						</div>
					</div>
					<div class="box-content">
						<div class="row-fluid">
						<div class="span6">
						<div id="DataTables_Table_0_length" class="dataTables_length">
						<label>
						<select name="DataTables_Table_0_length" size="1" aria-controls="DataTables_Table_0">
						<option value="10" selected="selected">10</option>
						<option value="25">25</option>
						<option value="50">50</option>
						<option value="100">100</option>
						</select> 
						records per page
						</label>
						</div>
						</div>
						<div class="span6">
						<div class="dataTables_filter" id="DataTables_Table_0_filter">
						<label>Search: <input type="text" aria-controls="DataTables_Table_0"></label>
						</div>
						</div>
						</div>
						<table class="table table-striped table-bordered bootstrap-datatable datatable">
						  <thead>
							  <tr>
								  <th>标题</th>
								  <th>所属分类</th>
								  <th>作者</th>
								  <th>图片</th>
								  <th>语言</th>
								  <th>来源</th>
								  <th>状态</th>
								  <th>添加时间</th>
								  <th>操作</th>
							  </tr>
						  </thead>   
						  <tbody>
						  <?php foreach ($page->items as $item):?>
							<tr>
								<td><?php echo $item->title;?></td>
								<td class="center"><?php echo $item->category_id;?></td>
								<td class="center"><?php echo $item->author;?></td>
								<td><?php echo $item->image;?></td>
								<td><?php echo $item->language;?></td>
								<td><?php echo $item->from;?></td>
								<td class="center">
									<span class="label label-success"><?php echo $item->status;?></span>
								</td>
								<td><?php echo $item->ctime;?></td>
								<td class="center">
									<a class="btn btn-success" href="#">
										<i class="halflings-icon white zoom-in"></i>  
									</a>
									<a class="btn btn-info" href="#">
										<i class="halflings-icon white edit"></i>  
									</a>
									<a class="btn btn-danger" href="#">
										<i class="halflings-icon white trash"></i> 
									</a>
								</td>
							</tr>
							<?php endforeach;?>
						</tbody>
					  </table> 
					  <div class="row-fluid">
						  <!--div class="span12">
						  	<div class="dataTables_info" id="DataTables_Table_0_info">Showing 1 to 10 of 10 entries</div>
						  </div-->
						  <div class="span12 center">
							  <div class="dataTables_paginate paging_bootstrap pagination">
						  	  Showing 1 to 10 of 10 entries
								  <ul>
									  <li class="prev disabled"><a href="#">← Previous</a></li>
									  <li class="active"><a href="#">1</a></li>
									  <li class="next disabled"><a href="#">Next → </a></li>
								  </ul>
							  </div>
						  </div>
					  </div>           
					</div>
				</div><!--/span-->
			
			</div><!--/row-->
