

<div class="control-group">
	<label class="control-label" for="typeahead">原来分类</label>
	<div class="controls">
		<select id="selectError3" name="engine">
			<option value="PHP">最近新闻</option>
			<option value="Smarty">Smarty</option>
			<option value="Volt">Volt</option>

		</select>
	</div>
</div>


<div class="control-group">
	<label class="control-label" for="typeahead">目标分类</label>
	<div class="controls">
		<select id="selectError3" name="engine">
			<option value="PHP">黄金评论</option>
			<option value="Smarty">Smarty</option>
			<option value="Volt">Volt</option>

		</select>
	</div>
</div>
