<script type="text/javascript">


</script>
<div class="row-fluid sortable">		
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon user"></i><span class="break"></span><?php ?></h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
            </div>
        </div>
        
        <div class="box-content">
            <div class="row-fluid">
							<div class="">
								<div class="" id="" style="float:left">
									<a href="/album/upload"><input  type="button" value="上传图片" class="btn btn-primary btn-search" /></a>
								</div>
							</div>
						</div>
           
            
            <table class="table table-striped table-bordered bootstrap-datatable datatable" style="margin-top: 30px;">  
                
                <div style="margin-top: 20px;">  
                    
                        <?php 
//                        
//                    header('Content-type: image/png;');    
                    $pictures_arr = $this->objToArray->ohYeah($image);
                    
                    foreach($pictures_arr as $vs){
                    ?>
                    <div style="float: left;width: 200px;margin-left: 22px;margin-top: 22px;">
						<a href="/image/raw/<?php echo $folder;?>/<?php echo $vs['file']['filename'];?>">
							<img src="/image/thumbnail/<?php echo $folder;?>/<?php echo $vs['file']['filename'];?>" />
						</a>
					</div>
                    <?php }?>
                   
                </div>
            </table>   
            
        </div>
    </div><!--/span-->

</div><!--/row-->
<script language="javascript" type="text/javascript">
   
</script>





